#!/usr/bin/env python3
"""Build snippets.js from the "cut copy" note in the Obsidian vault.

Usage: build.py NOTE.md [OUT.js]   (OUT defaults to snippets.js next to this script)

Note format:
    ---
    heading: cut copy
    subhead: an incomplete catalog of the copy they cut
    shuffle: false
    ---
    - billboard | Airbnb | the line
    - social | Twitter | first line of a post
    	second line (indented lines are line breaks in the same snippet)
    - tagline | | no client

Only top-level "- " bullets with a known kind become snippets; any other line is ignored, so the
note can hold headings and working notes. Kinds (and short forms): billboard (bb), headline (head),
tagline (tag), oneliner (one-liner, line), paragraph (para), social (post, tweet).
"""
import json
import re
import sys
from pathlib import Path

KINDS = {
    "billboard": "billboard", "bb": "billboard",
    "headline": "headline", "head": "headline",
    "tagline": "tagline", "tag": "tagline",
    "oneliner": "oneliner", "one-liner": "oneliner", "line": "oneliner",
    "paragraph": "paragraph", "para": "paragraph",
    "social": "social", "post": "social", "tweet": "social",
}
DEFAULTS = {"heading": "cut copy", "subhead": "an incomplete catalog of the copy they cut", "shuffle": False}
MARKER = re.compile(r"\s*<!--r[0-9a-z]+-->\s*$")  # Reminders-sync markers, in case the note is ever synced


def parse(text):
    site, snippets, warnings = dict(DEFAULTS), [], []
    lines = text.splitlines()
    if lines and lines[0].strip() == "---":
        end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
        if end:
            for l in lines[1:end]:
                k, _, v = l.partition(":")
                k, v = k.strip(), v.strip().strip('"')
                if k in ("heading", "subhead"):
                    site[k] = v
                elif k == "shuffle":
                    site[k] = v.lower() in ("true", "yes", "1")
            lines = lines[end + 1:]
    cur = None
    for n, raw in enumerate(lines, 1):
        line = MARKER.sub("", raw.rstrip())
        if line.startswith("- "):
            cur = None
            parts = [p.strip() for p in line[2:].split("|", 2)]
            kind = KINDS.get(parts[0].lower()) if parts else None
            if not kind or len(parts) < 2:
                if "|" in line:
                    warnings.append("line %d: unknown kind %r, skipped" % (n, parts[0]))
                continue
            client, body = (parts[1], parts[2]) if len(parts) == 3 else ("", parts[1])
            if not body:
                warnings.append("line %d: no text, skipped" % n)
                continue
            cur = {"kind": kind, "client": client, "text": body}
            snippets.append(cur)
        elif cur and line[:1] in ("\t", " ") and line.strip():
            cur["text"] += "\n" + line.strip()
        elif not line.strip():
            continue
        else:
            cur = None
    return site, snippets, warnings


def render(site, snippets):
    return ("// Generated by build.py from the \"cut copy\" note. Edit the note, not this file.\n"
            "const SITE = %s;\n\nconst SNIPPETS = %s;\n" % (
                json.dumps(site, ensure_ascii=False, indent=2),
                json.dumps(snippets, ensure_ascii=False, indent=2)))


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    note = Path(sys.argv[1])
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).with_name("snippets.js")
    site, snippets, warnings = parse(note.read_text(encoding="utf-8"))
    for w in warnings:
        print("warning: " + w, file=sys.stderr)
    if not snippets:
        sys.exit("no snippets found in %s; not overwriting %s" % (note, out))
    out.write_text(render(site, snippets), encoding="utf-8")
    print("%d snippets -> %s" % (len(snippets), out))


if __name__ == "__main__":
    main()
